version: '2'
services:
    pfg-app:
        image: pfg
        external_links:
            - pfg-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pfg?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    pfg-mysql:
        extends:
            file: mysql.yml
            service: pfg-mysql
